# Generated by Django 6.0.7 on 2026-08-15 18:54

"""Adds `CreditSource.BOOKING_REFUNDED` — slice 11.

Choices only. Django does not express `choices` as a database constraint, so
this alters no column, rewrites no table and takes no lock worth naming; the
existing `max_length=24` already fits the new 16-character value. Reviewed by
hand per CLAUDE.md §11, and recorded as harmless rather than assumed to be.
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_payment_refund_due_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='source',
            field=models.CharField(choices=[('late_cancellation', 'Cancelled inside the refund window'), ('shop_goodwill', 'Issued by the shop'), ('booking_refunded', 'Returned when a credit-paid booking was cancelled')], default='late_cancellation', max_length=24),
        ),
    ]
