# Generated by Django 5.1.6 on 2026-07-24 14:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.contrib.postgres.search import SearchVector
from django.db import migrations, models


def backfill_search_vector(apps, schema_editor):
    """Populate the new column for listings that predate it (title A, desc B)."""
    Listing = apps.get_model("catalog", "Listing")
    Listing.objects.update(
        search_vector=SearchVector("title", weight="A", config="english")
        + SearchVector("description", weight="B", config="english")
    )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(editable=False, null=True),
        ),
        migrations.RunPython(backfill_search_vector, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['status', 'price'], name='catalog_lis_status_e9f776_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='listing_search_gin'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=django.contrib.postgres.indexes.GinIndex(fields=['attributes'], name='listing_attrs_gin'),
        ),
    ]
