# Generated by Django 6.0.7 on 2026-08-01 15:33

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import shops.slugs
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0003_alter_staffinvite_options_alter_staffinvite_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=63, unique=True, validators=[shops.slugs.validate_shop_slug])),
                ('address', models.CharField(blank=True, max_length=200)),
                ('area', models.CharField(blank=True, help_text="Neighbourhood, e.g. 'Wood Ave'", max_length=80)),
                ('directions_url', models.URLField(blank=True, help_text="Opened by the client's Directions link")),
                ('phone', models.CharField(blank=True, max_length=16)),
                ('logo_url', models.URLField(blank=True)),
                ('accent_color', models.CharField(blank=True, help_text='Hex, e.g. #C2521F. Falls back to the BookNasi accent when blank.', max_length=7)),
                ('buffer_minutes', models.PositiveSmallIntegerField(default=10, help_text='Turnaround between appointments. Shop-wide in v1.', validators=[django.core.validators.MaxValueValidator(120)])),
                ('hold_ttl_minutes', models.PositiveSmallIntegerField(default=3, help_text='How long an unpaid slot is held while the STK push is outstanding.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)])),
                ('refund_window_hours', models.PositiveSmallIntegerField(default=24, help_text='Cancel earlier than this and the deposit is refundable. CLAUDE.md §12.', validators=[django.core.validators.MaxValueValidator(168)])),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs.organization')),
            ],
            options={
                'db_table': 'shops',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)])),
                ('price', models.PositiveIntegerField(help_text='Whole shillings')),
                ('deposit_mode', models.CharField(choices=[('none', 'No deposit'), ('flat', 'Flat amount'), ('percent', 'Percentage of price')], default='percent', max_length=8)),
                ('deposit_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('25'), help_text='Shillings when mode is flat, a percentage when mode is percent.', max_digits=7, null=True)),
                ('deposit_amount', models.PositiveIntegerField(default=0, editable=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_publicly_listed', models.BooleanField(default=True, help_text="Owner's intent. Public bookability also requires a deposit — see is_publicly_bookable.")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs.organization')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='shops.shop')),
            ],
            options={
                'db_table': 'services',
                'ordering': ['name'],
                'default_manager_name': 'all_objects',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='OpeningHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('opens_at', models.TimeField(help_text='EAT wall-clock')),
                ('closes_at', models.TimeField(help_text='EAT wall-clock')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs.organization')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hours', to='shops.shop')),
            ],
            options={
                'db_table': 'opening_hours',
                'ordering': ['weekday', 'opens_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='ShopClosure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(help_text='Inclusive')),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs.organization')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='shops.shop')),
            ],
            options={
                'db_table': 'shop_closures',
                'ordering': ['starts_on'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('display_name', models.CharField(help_text="What clients see, e.g. 'Wanjiku'", max_length=80)),
                ('is_bookable', models.BooleanField(default=True, help_text="Appears in the client's stylist picker.")),
                ('is_active', models.BooleanField(default=True, help_text='Still works here at all.')),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='orgs.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs.organization')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='shops.shop')),
            ],
            options={
                'db_table': 'staff',
                'ordering': ['display_name'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField(help_text='Inclusive')),
                ('reason', models.CharField(blank=True, max_length=120)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave', to='shops.staff')),
            ],
            options={
                'verbose_name_plural': 'leave',
                'db_table': 'staff_leave',
                'ordering': ['starts_on'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='StaffService',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_override_minutes', models.PositiveSmallIntegerField(blank=True, help_text="Blank means this staff member takes the service's own duration.", null=True, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(600)])),
                ('is_offered', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_links', to='shops.service')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_links', to='shops.staff')),
            ],
            options={
                'db_table': 'staff_services',
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='services',
            field=models.ManyToManyField(related_name='staff', through='shops.StaffService', to='shops.service'),
        ),
        migrations.CreateModel(
            name='WorkingHours',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('starts_at', models.TimeField(help_text='EAT wall-clock')),
                ('ends_at', models.TimeField(help_text='EAT wall-clock')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs.organization')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='shops.staff')),
            ],
            options={
                'db_table': 'working_hours',
                'ordering': ['weekday', 'starts_at'],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('buffer_minutes__lte', 120)), name='shop_buffer_sane'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('hold_ttl_minutes__gte', 1), ('hold_ttl_minutes__lte', 30)), name='shop_hold_ttl_sane'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('refund_window_hours__lte', 168)), name='shop_refund_window_sane'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(('duration_minutes__gte', 5), ('duration_minutes__lte', 600)), name='service_duration_sane'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deposit_mode', 'none'), ('deposit_value__isnull', True)), models.Q(models.Q(('deposit_mode', 'none'), _negated=True), ('deposit_value__gt', 0)), _connector='OR'), name='service_deposit_value_matches_mode'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deposit_mode', 'percent'), _negated=True), ('deposit_value__lte', 100), _connector='OR'), name='service_percent_deposit_within_100'),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('deposit_mode', 'flat'), _negated=True), ('deposit_value__lte', models.F('price')), _connector='OR'), name='service_flat_deposit_not_above_price'),
        ),
        migrations.AddConstraint(
            model_name='openinghours',
            constraint=models.UniqueConstraint(fields=('shop', 'weekday'), name='one_opening_row_per_weekday'),
        ),
        migrations.AddConstraint(
            model_name='openinghours',
            constraint=models.CheckConstraint(condition=models.Q(('closes_at__gt', models.F('opens_at'))), name='opening_hours_close_after_open'),
        ),
        migrations.AddConstraint(
            model_name='shopclosure',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='closure_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='leave',
            constraint=models.CheckConstraint(condition=models.Q(('ends_on__gte', models.F('starts_on'))), name='leave_ends_after_it_starts'),
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.UniqueConstraint(fields=('staff', 'service'), name='one_link_per_staff_service'),
        ),
        migrations.AddConstraint(
            model_name='staffservice',
            constraint=models.CheckConstraint(condition=models.Q(('duration_override_minutes__isnull', True), models.Q(('duration_override_minutes__gte', 5), ('duration_override_minutes__lte', 600)), _connector='OR'), name='staff_service_override_sane'),
        ),
        migrations.AddConstraint(
            model_name='staff',
            constraint=models.UniqueConstraint(condition=models.Q(('membership__isnull', False)), fields=('shop', 'membership'), name='one_staff_profile_per_membership_per_shop'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.UniqueConstraint(fields=('staff', 'weekday'), name='one_working_row_per_weekday'),
        ),
        migrations.AddConstraint(
            model_name='workinghours',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='working_hours_end_after_start'),
        ),
    ]
