# Generated by Django 6.0.7 on 2026-08-01 17:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0003_alter_staffinvite_options_alter_staffinvite_managers'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='booking_horizon_days',
            field=models.PositiveSmallIntegerField(default=60, help_text='How far ahead the public can book. Bounds the damage one script can do.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)]),
        ),
        migrations.AddField(
            model_name='shop',
            name='min_deposit_amount',
            field=models.PositiveIntegerField(default=50, help_text='Floor for every deposit at this shop, in whole shillings.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5000)]),
        ),
        migrations.AddField(
            model_name='shop',
            name='min_lead_minutes',
            field=models.PositiveSmallIntegerField(default=30, help_text='Public bookings must start at least this far ahead. Ignored for walk-ins.', validators=[django.core.validators.MaxValueValidator(1440)]),
        ),
        migrations.AddField(
            model_name='shop',
            name='slot_interval_minutes',
            field=models.PositiveSmallIntegerField(default=15, help_text='Slots land on a clock grid this many minutes apart. Slice 3, decision (a).', validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AddConstraint(
            model_name='service',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(models.Q(('deposit_amount', 0), ('deposit_mode', 'none')), models.Q(('deposit_amount', 0), ('price', 0)), models.Q(models.Q(('deposit_mode', 'none'), _negated=True), ('deposit_amount__gt', 0)), _connector='OR'), ('deposit_amount__lte', models.F('price'))), name='service_deposit_amount_within_price'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('slot_interval_minutes__gte', 5), ('slot_interval_minutes__lte', 60)), name='shop_slot_interval_sane'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('min_lead_minutes__lte', 1440)), name='shop_min_lead_sane'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('booking_horizon_days__gte', 1), ('booking_horizon_days__lte', 365)), name='shop_booking_horizon_sane'),
        ),
        migrations.AddConstraint(
            model_name='shop',
            constraint=models.CheckConstraint(condition=models.Q(('min_deposit_amount__gte', 1), ('min_deposit_amount__lte', 5000)), name='shop_min_deposit_sane'),
        ),
    ]
