# Generated by Django 6.0.7 on 2026-08-01 18:06

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # `staff_id WITH =` inside a GiST exclusion constraint needs btree_gist.
        # Django does not infer this, and without it the ordering below is luck:
        # on a fresh database the CREATE CONSTRAINT can run first and fail with
        # "data type uuid has no default operator class for access method gist",
        # which reads like a modelling error rather than a missing extension.
        ('core', '0001_btree_gist'),
        ('clients', '0001_initial'),
        ('orgs', '0003_alter_staffinvite_options_alter_staffinvite_managers'),
        ('shops', '0002_scheduling_policy_and_deposit_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_range', django.contrib.postgres.fields.ranges.DateTimeRangeField(help_text='UTC. Half-open: the end instant belongs to the next appointment.')),
                ('status', models.CharField(choices=[('pending_payment', 'Awaiting payment'), ('confirmed', 'Confirmed'), ('in_progress', 'In progress'), ('completed', 'Completed'), ('no_show', 'No show'), ('cancelled', 'Cancelled')], db_index=True, default='pending_payment', max_length=16)),
                ('source', models.CharField(choices=[('online', 'Online'), ('walk_in', 'Walk-in'), ('staff', 'Booked by staff')], max_length=8)),
                ('price_snapshot', models.PositiveIntegerField()),
                ('deposit_snapshot', models.PositiveIntegerField()),
                ('duration_snapshot', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='clients.client')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='orgs.organization')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='shops.service')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='shops.shop')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='shops.staff')),
            ],
            options={
                'db_table': 'appointments',
                'ordering': ['time_range'],
                'indexes': [models.Index(fields=['staff', 'status'], name='appt_staff_status_idx'), models.Index(fields=['shop', 'status'], name='appt_shop_status_idx')],
                'constraints': [django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ('pending_payment', 'confirmed', 'in_progress'))), expressions=[('staff', '='), ('time_range', '&&')], name='no_overlapping_appointments'), models.CheckConstraint(condition=models.Q(('deposit_snapshot__lte', models.F('price_snapshot'))), name='appointment_deposit_within_price'), models.CheckConstraint(condition=models.Q(('duration_snapshot__gte', 1)), name='appointment_has_a_duration'), models.CheckConstraint(condition=models.Q(('time_range__isempty', False)), name='appointment_range_not_empty')],
            },
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
