# Generated by Django 6.0.7 on 2026-08-01 15:24

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='membership',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
