# Generated by Django 6.0.7 on 2026-08-01 15:29

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_membership_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffinvite',
            options={'default_manager_name': 'all_objects'},
        ),
        migrations.AlterModelManagers(
            name='staffinvite',
            managers=[
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
